package com.loan.calculator.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF32A887)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA6F4D8)
val md_theme_light_onPrimaryContainer = Color(0xFF00341A)
val md_theme_light_secondary = Color(0xFF5E7F6B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE1F7EE)
val md_theme_light_onSecondaryContainer = Color(0xFF1C3829)
val md_theme_light_tertiary = Color(0xFF3A7A4C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBBF4C9)
val md_theme_light_onTertiaryContainer = Color(0xFF002110)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFBFDFC)
val md_theme_light_onBackground = Color(0xFF1A1C1B)
val md_theme_light_surface = Color(0xFFFBFDFC)
val md_theme_light_onSurface = Color(0xFF1A1C1B)

val md_theme_dark_primary = Color(0xFF8AF8D0)
val md_theme_dark_onPrimary = Color(0xFF00573A)
val md_theme_dark_primaryContainer = Color(0xFF1F7A53)
val md_theme_dark_onPrimaryContainer = Color(0xFFA6F4D8)
val md_theme_dark_secondary = Color(0xFFC5EAD8)
val md_theme_dark_onSecondary = Color(0xFF313D34)
val md_theme_dark_secondaryContainer = Color(0xFF47534B)
val md_theme_dark_onSecondaryContainer = Color(0xFFE1F7EE)
val md_theme_dark_tertiary = Color(0xFFA0D8AF)
val md_theme_dark_onTertiary = Color(0xFF06391C)
val md_theme_dark_tertiaryContainer = Color(0xFF235235)
val md_theme_dark_onTertiaryContainer = Color(0xFFBBF4C9)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1A1C1B)
val md_theme_dark_onBackground = Color(0xFFE2E3E1)
val md_theme_dark_surface = Color(0xFF1A1C1B)
val md_theme_dark_onSurface = Color(0xFFE2E3E1)